[package]
name = "pkglistgen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "3.2", features = ["derive"] }
owo-colors = { version = "3.4", features = ["supports-colors"] }
